# Generated by Django 5.0 on 2025-10-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoUniJose', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='fecha_regsitro',
            new_name='fecha_registro',
        ),
    ]
